apiVersion: v1
name: pipes-chart
description: A Helm chart for the ACK service controller for Amazon EventBridge Pipes (Pipes)
version: v0.0.1
appVersion: v0.0.1
home: https://github.com/aws-controllers-k8s/pipes-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/pipes-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: Pipes Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/pipes-maintainer
keywords:
  - aws
  - kubernetes
  - pipes
